FROM httpd:2.4
COPY ./htdocs/ /usr/local/apache2/htdocs/
COPY ./conf/httpd.conf /usr/local/apache2/conf/httpd.conf
RUN mkdir -p /usr/local/apache2/conf/sites/
COPY ./conf/sites/gapid.surroundaustralia.com.conf /usr/local/apache2/conf/sites/gapid.surroundaustralia.com.conf

RUN apt update
RUN apt install python3 python3-pip -y
WORKDIR /app
COPY requirements.txt test_pid_rules.py tests ./
RUN pip3 install -r requirements.txt
