FROM httpd:2.4
COPY ./htdocs/ /usr/local/apache2/htdocs/
COPY ./conf/httpd.conf /usr/local/apache2/conf/httpd.conf
RUN mkdir -p /usr/local/apache2/conf/sites/
COPY ./conf/sites/ /usr/local/apache2/conf/sites/
RUN mkdir -p /usr/local/pid_tests
COPY tests/test_redirects.py /usr/local/PID_tests/test_redirects.py
COPY tests/rule-cases.json /usr/local/PID_tests/rule-cases.json

RUN apt update
RUN apt install python3 python3-pip -y
WORKDIR /app
COPY requirements.txt ./
RUN pip3 install -r requirements.txt
